version: "3.8"
services:
  webrtc-detection:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./models:/app/models
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
